language: csharp
mono: none
dist: xenial
dotnet: 3.1
before_install:
  - sudo apt-get install dotnet-sdk-3.1
install:
  - dotnet restore "./src/FiscalBr.sln"
script:
  - dotnet build "./src/FiscalBr.Common/FiscalBr.Common.csproj" -c Release -f netstandard2.1
  - dotnet build "./src/FiscalBr.Dimob/FiscalBr.Dimob.csproj" -c Release -f netstandard2.1
  - dotnet build "./src/FiscalBr.ECF/FiscalBr.ECF.csproj" -c Release -f netstandard2.1
  - dotnet build "./src/FiscalBr.EFDContribuicoes/FiscalBr.EFDContribuicoes.csproj" -c Release -f netstandard2.1
  - dotnet build "./src/FiscalBr.EFDFiscal/FiscalBr.EFDFiscal.csproj" -c Release -f netstandard2.1
  - dotnet build "./src/FiscalBr.Sintegra/FiscalBr.Sintegra.csproj" -c Release -f netstandard2.1
  - dotnet build "./src/FiscalBr.Tests/FiscalBr.Tests.csproj" -c Release -f netcoreapp3.1
  - dotnet test "./src/FiscalBr.Tests/FiscalBr.Tests.csproj"
